### ISSUE TITLE
Anyway to not have an event only in multiplayer?

### ISSUE THREAD

**Issue by Xyphien** [KageDesu/Alpha-NET-Z#1]
I'd like to completely skip an event if you're playing the game in multiplayer using the alpha-net-z. Is there anyway to bypass entire events if you're using this versus if you're playing solo?

**Comment by KageDesu** [comment]
You can use condition switch inside event, with script call: nAPI.isNetworkGame(); (is current game in multiplayer?)


More info here: https://github.com/KageDesu/Alpha-NET-Z/wiki/Script-calls-User-API

**Comment by Xyphien** [comment]
> You can use condition switch inside event, with script call: nAPI.isNetworkGame(); (is current game in multiplayer?)
> 
> More info here: https://github.com/KageDesu/Alpha-NET-Z/wiki/Script-calls-User-API

So do I do something like nAPI.isNetworkGame() == on;
or am I simply copying and pasting:
nAPI.isNetworkGame() - is current game in multiplayer?
If so, what exactly does this mean? Does that mean I paste that whenever I want something to not be in multiplayer, or when I want something to be put in multiplayer? The link you sent has nothing on that at all, and it actually shows it slightly different than the one you posted above.

**Comment by Xyphien** [comment]
Or would I do it like nAPI.isNetworkGame() == "on";
or nAPI.isNetworkGame() == (on);

or 
nAPI.isNetworkGame(on) == true;

or

nAPI.isNetworkGame(true) == on;

I have literally no idea which one to do
