### ISSUE TITLE
error "Server not response in time"

### ISSUE THREAD

**Issue by Drew1972-1972** [KageDesu/Alpha-NET-Z#3]
I don't know what to do D=>

**Comment by KageDesu** [comment]
The server has "crashed", now it has been rebooted and is working again.

**Comment by Drew1972-1972** [comment]
> El servidor se ha "bloqueado", ahora se ha reiniciado y está funcionando de nuevo.

thankssssssssssssss, sorry fi my english is incorrect, i'talk spanish
